#' Returns a Knock-Knock joke
#' 
#' Returns a random knock-knock joke of the 300+ knock-knock jokes pre-installed. 
#' 
#' @examples 
#' 
#' knock_knock()
#'   
#' @export
#' 
knock_knock <- function() {
  
  jokes <- c("\n\nKnock knock.\n\nWho’s there?\n\nCow says.\n\nCow says who?\n\nNo, a cow says mooooo!\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nA little old lady.\n\nA little old lady who?\n\nAll this time, I had no idea you could yodel.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nEurope.\n\nEurope who?\n\nNo I’m not!\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nEtch.\n\nEtch who?\n\nBless you, friend.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nRobin.\n\nRobin who?\n\nRobin you, now hand over the cash.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nCash.\n\nCash who?\n\nNo thanks, I’ll have some peanuts.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nMustache.\n\nMustache who?\n\nI mustache you a question, but I’ll shave it for later.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nTank.\n\nTank who?\n\nYou’re welcome.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nI smell mop.\n\nI smell mop who?\n\nEw.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nI eat mop.\n\nI eat mop who?\n\nThat’s revolting.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nYa.\n\nYa who?\n\nYahoo! I’m just as psyched to see you!\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nVoodoo.\n\nVoodoo who?\n\nVoodoo you think you are, asking me so many questions?\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nSpell.\n\nSpell who?\n\nOkay, okay: W. H. O.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nCandice.\n\nCandice who?\n\nCandice door open, or what?\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nBoo.\n\nBoo who?\n\nNo need to cry, it’s only a joke.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nStopwatch.\n\nStopwatch who?\n\nStopwatch you’re doing and pay attention!\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nTo.\n\nTo who?\n\nIt’s to whom.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s There?\n\nDewey.\n\nDewey who?\n\nDewey have to use a condom every time?\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nHoney bee.\n\nHoney bee who?\n\nHoney bee a dear and open up, would you?\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nLettuce.\n\nLettuce who?\n\nLettuce in, it’s cold out here!\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nMikey.\n\nMikey who?\n\nMikey doesn’t work so help me out, would you?\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nDwayne.\n\nDwayne who?\n\nDwayne the bathtub already. I’m drowning!\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nRazor.\n\nRazor who?\n\nRazor hands, this is a stick up!\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nOlive.\n\nOlive who?\n\nOlive you. Do you love me too?\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nAlec.\n\nAlec who?\n\nAlec-tricity. Ain’t that a shocker?\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nHowl.\n\nHowl who?\n\nHowl you know unless you open the door?\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nIran.\n\nIran who?\n\nIran all the way here. Let me in already!\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nSays.\n\nSays who?\n\nSays me, that’s who.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nSnow.\n\nSnow who?\n\nSnow use askin’ when you can just open.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nSome.\n\nSome who?\n\nSome day you’ll recognize me, hopefully.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nStupid.\n\nStupid who?\n\nStupid you, that’s who.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nNeedle.\n\nNeedle who?\n\nNeedle little help gettin’ through.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nThermos.\n\nThermos who?\n\nThermos be a better way to get through to you.\n\n\n", 
             "\n\nKnock Knock\n\nWho’s there?\n\nWater.\n\nWater who?\n\nWater you doing? Just open the door!\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nAmos.\n\nAmos who?\n\nA mosquito.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nDozen.\n\nDozen who?\n\nDozen anyone wanna let me in?\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nNanna.\n\nNanna who?\n\nNanna your business, that’s who.\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nEuripides.\n\nEuripides who?\n\nEuripides jeans, you pay for ’em, okay?\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nAnnie.\n\nAnnie who?\n\nAnnie way you can let me in soon?\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nCanoe.\n\nCanoe who?\n\nCanoe come out or what?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nAdore.\n\nAdore who?\n\nAdore is between us. Open up!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nAmanda\n\nAmanda who?\n\nA man da fix your sink!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nAmish!\n\nAmish who?\n\nYou're not a shoe!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nAl\n\nAl who?\n\nAl give you a kiss if you open this door!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nAlfie\n\nAlfie who?\n\nAlfie terrible if you leave!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nAvenue.\n\nAvenue who?\n\nAvenue knocked on this door before?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there \n\nAmish \n\nAmish Who? \n\nAw How sweet. I miss you too.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nAlien\n\nAlien who?\n\nJust how many aliens do you know?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nA herd.\n\nA herd who?\n\nA herd you were home, so I came over!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nAbby.\n\nAbby who?\n\nAbby birthday to you!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nAnnie.\n\nAnnie who?\n\nAnnie body home?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nAbby\n\nAbby who?\n\nA bee just stung me!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nArmageddon.\n\nArmageddon who?\n\nArmageddon a little bored. Let’s go out.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nAndrew!\n\nAndrew who?\n\nAndrew a picture!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nAmma\n\nAmma who?\n\nAmma not going to tell you!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nAnnie\n\nAnnie who?\n\nAnnie one you like!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nArgo\n\nArgo who?\n\nArgo down the shops if you aren't going to let me in!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nBoo.\n\nBoo who?\n\nGosh, don’t cry it’s just a knock knock joke.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nBritney Spears\n\nBritney Spears who?\n\nKnock, knock - oops i did it again.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nBroccoli.\n\nBroccoli who?\n\nBroccoli doesn't have a last name, silly.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nBroken Pencil.\n\nBroken Pencil who.\n\nNever mind it's pointless!\n\n\n", 
             "\n\nKnock, knock. \n\nWho's there? \n\nButch, Jimmy and Joe. \n\nButch, Jimmy, and Joe Who? \n\nButch your arms around me, Jimmy a kiss, and let's Joe.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nBarbara\n\nBarbara who?\n\nBarbara black sheep, have you any wool...\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nBed\n\nBed who?\n\nBed you can't guess who I am!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nBen\n\nBen who?\n\nBen knocking on this door all morning, let me in!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nBruce \n\nBruce who?\n\nI Bruce easily, don't hit me !\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nBurglar\n\nBurglar who?\n\nBurglars don't knock!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nButter\n\nButter who?\n\nButter be quick, I have to go to the bathroom!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nBuddha\n\nBuddha who?\n\nBuddha this slice of bread for me!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nCaesar.\n\nCaesar who?\n\nCaesar quick, she’s running away.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nControl freak.\n\nCo…\n\nYou should say \"Control freak who\" now.\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nCanoe.\n\nCanoe who?\n\nCanoe help me with my work?\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nCD.\n\nCD who?\n\nCD guy on your doorstep?\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nClaire.\n\nClaire who?\n\nClaire the way, I’m coming through!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nCows go.\n\nCow's go who?\n\nNo, silly. Cows go Moo!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\ninterrupting cow.\n\ninterrupting c-\n\nMooooo!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nCash.\n\nCash who?\n\nYes! I've always known you were a bit nutty!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nCook.\n\nCook who?\n\nYes you are!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nComb\n\nComb who?\n\nComb on down and I'll tell you!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nCheese\n\nCheese who?\n\nCheese a nice girl.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nChick!\n\nChick who ?\n\nChick your oven, I can smell burning !\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nCupid!\n\nCupid who?\n\nCupid quiet in there.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nCows\n\nvCows who?\n\nCows go moo not who!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nDozen.\n\nDozen who?\n\nDozen all this knocking bother you already?\n\n\n", 
             "\n\nKnock, knock. \n\nWho's there ? \n\nDishes! \n\nDishes who? \n\nDishes the Police come out with your hands up.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there? \n\nDwayne! \n\nDwayne who? \n\nDwayne the bathtub, I'm drowning!!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nDoris.\n\nDoris who?\n\nThe Doris locked, why do you think I'm knocking?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nDozen.\n\nDozen who?\n\nDozen anybody want to let me in?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nDouble\n\nDouble who?\n\nW!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nDish.\n\nDish who?\n\nDish is a nice place!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\ninterrupting doctor.\n\ninterr…\n\nYou've got cancer.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nDaisy \n\nDaisy who? \n\nDaisy me rollin, they hatin\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nEgg.\n\nEgg who?\n\nEggstremely disappointed you still don’t recognize me.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nEtch.\n\nEtch who?\n\nBless you.\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nEgg.\n\nEgg who?\n\nEggcited to see me?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nEarl\n\nEarl who?\n\nEarl be glad to get to bed, I'm tired.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nEars\n\nEars who?\n\nEars another knock knock jokes for you!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nEmma\n\nEmma who?\n\nEmma bit cold out here, can you let me in?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nEurope\n\nEurope who?\n\nEurope early this morning!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nFelix\n\nFelix who?\n\nFelix my lolly, I'll whack him.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nFangs\n\nFangs who?\n\nFangs for letting me in!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nFerdie!\n\nFerdie who?\n\nFerdie last time open this door!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nFiddle\n\nFiddle?\n\nFiddle make you happy I'll tell you!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nFrank!\n\nFrank who?\n\nFrank you for being my friend!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there? \n\nFigs. \n\nFigs who? \n\nFigs the doorbell, it’s broken!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nFlea\n\nFlea who?\n\nFlea blind mice!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nFossil\n\nFossil who?\n\nFossil last time, open the door!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nFork\n\nFork who?\n\nFork-get it, I'm leaving!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nFrance\n\nFrance who?\n\nFrance of the family!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nFrank\n\nFrank who?\n\nFrank you for being my friend!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nGorilla!\n\nGorilla who?\n\nGorilla burger! I've got the buns!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nGarden\n\nGarden who?\n\nGarden the treasure, it's precious!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nGerald\n\nGerald who?\n\nIt's Gerald friend from school!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nGandhi\n\nGandhi who?\n\nGandhi come out and play?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nGino\n\nGino who?\n\nGino me or not, now open the door!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nGoose\n\nGoose who?\n\nGoose who's knocking at your door again!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nGrub\n\nGrub who?\n\nGrub hold of my hand and lets go!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nGladys\n\nGladys who?\n\nGladys Friday, finally the weekend starts!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nHatch\n\nHatch who?\n\nGod bless you!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nHoo.\n\nHoo who?\n\nAre you a owl?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nHada!\n\nHada who?\n\nHad a great time, how about you?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nHarry.\n\nHarry who?\n\nHarry up, it’s cold out here!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nHeaven\n\nHeaven who?\n\nHeaven seen you for a long time.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nHey\n\nHey who?\n\nHey ho, hey ho, it's off to work we go!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nHammond\n\nHammond who?\n\nHammond eggs!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nHand\n\nHand who?\n\nHandover your money!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nHarry\n\nHarry who?\n\nHarry up and answer this door!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nHip\n\nHip who?\n\nHippopotamus.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nHockey\n\nHockey who?\n\nHockey doesn't work, so I had to knock!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nHouse \n\nHouse who?\n\nHouse you doing?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nHoward\n\nHoward who?\n\nHoward you like to be knocking for a change ?\n\n\n", 
             "\n\nKnock, knock. \n\nWho's there? \n\nIran! \n\nIran who? \n\nIran over here to tell you this!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nI eat mop.\n\nI eat mop who?\n\nDammit, man, that is way too much information!\n\n\n", 
             "\n\nKnock, knock. \n\nWho’s there? \n\nIva. \n\nIva who? \n\nI’ve a sore hand from knocking!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nIsabell.\n\nIsabell who?\n\nIs a bell working?\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nIvor.\n\nIvor who?\n\nIvor you let me in or I`ll climb through the window.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nIce cream! \n\nIce cream who? \n\nIce cream if you don't let me in!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nUrine.\n\nUrine who?\n\nUrine trouble if you don’t open the door.\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nIrish.\n\nIrish who?\n\nIrish you a nice day.\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nIona.\n\nIona who?\n\nIona new car!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nIcy.\n\nIcy who?\n\nYou see me, do you need glasses or something?\n\n\n", 
             "\n\nKnock, knock\n\nWho’s there?\n\nJustin.\n\nJustin who?\n\nJust in the neighborhood, thought I would drop by.\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nJess.\n\nJess who?\n\nJess let me in.\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nJustin.\n\nJustin who?\n\nJustin time for dinner.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nJam\n\nJam who?\n\nJam mind, I'm trying to get in!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nJamaica\n\nJamaica who ?\n\nJamaica mistake? Just let me in!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nJava\n\nJava who?\n\nJava dog in your house, I hear one barking!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nJester\n\nJester who?\n\nJester silly old man!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nJim \n\nJim who?\n\nJim mind if I come in?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nJoe \n\nJoe who?\n\nJoe away, I'm not talking to you.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nKeanu\n\nKeanu who?\n\nKeanu let me in, it's cold out here !\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nKenya\n\nKenya who?\n\nKenya guess who is it?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nKermit\n\nKermit who?\n\nKermit a crime and you'll get locked up!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nKanga\n\nKanga who?\n\nActually, it’s kangaroo!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nKen.\n\nKen who?\n\nKen I come in?\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nLuke.\n\nLuke who?\n\nLuke through the the peep hole and find out.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nLee\n\nLee who?\n\nLee me alone - I've got a headache!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nLettuce.\n\nLettuce who?\n\nLettuce in it’s cold out here!\n\n\n", 
             "\n\nWhy did Lisa fall of the swing?\n\nBecause she had no arms.\n\nKnock, knock!\n\nWho’s there?\n\nWell, not Lisa, that’s for sure.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nLeaf?\n\nLeaf who?\n\nLeaf me alone!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nA little boy\n\nA little boy who?\n\nA little boy who can't reach the doorbell.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nLego\n\nLego who?\n\nLego of me and I'll tell you!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nLes\n\nLes who?\n\nLes go out for a picnic!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nLion\n\nLion who?\n\nLion on your doorstep, open up!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nLock\n\nLock who?\n\nLock who it is, after all this time!\n\n\n", 
             "\n\nKnock, knock! \n\nWho’s there?\n\nMoustache!\n\nMoustache who?\n\nI thought I moustache you a question, but I can shave it for tomorrow.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nMango!\n\nMango who?\n\nMango to the door and just answer it!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nMajor.\n\nMajor who?\n\nMajor day with this joke, haven’t I?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nMajor\n\nMajor who?\n\nMajor answer didn't I!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nMary\n\nMary who?\n\nMarry me?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nMikey.\n\nMikey who?\n\nMikey doesn't fit in the keyhole.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nMax\n\nMax who?\n\nMax no difference. Open the door!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nMeg\n\nMeg who?\n\nMeg up your mind - Let me in!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nNoah.\n\nNoah who?\n\nNoah good place we can get something to eat?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nNoise\n\nNoise who?\n\nNoise to see you!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nNun\n\nNun who?\n\nNun of your business!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nNana.\n\nNana who?\n\nNana your business!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nNobel.\n\nNobel who?\n\nNo bell, I knock.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nNose\n\nNose who?\n\nI nose plenty more knock knock jokes!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nOrange\n\nOrange who?\n\nOrange you sick of these knock-knock jokes?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nObi Wan\n\nObi Wan who?\n\nObi Wan of the good guys!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nOmelet\n\nOmelet who?\n\nOmelet'in you kiss me!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nOscar\n\nOscar who?\n\nOscar a silly question, get a silly answer!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nOwl\n\nOwl who?\n\nOwl be sad if you don't let me in!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nOzzie\n\nOzzie who?\n\nOzzie you later!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nPhilip\n\nPhilip who?\n\nPhilip up my glass please, I'm thirsty!\n\n\n", 
             "\n\nKnock, knock\n\nWho's there?\n\nPoll\n\nPoll who?\n\nPolice!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nPolice.\n\nPolice who?\n\nPolice hurry up, it’s chilly outside!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nPassion\n\nPassion who?\n\nJust Passion by and thought I'd pop in!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nPasta\n\nPasta who?\n\nPasta salt please!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nPhone\n\nPhone who?\n\nPhonely I'd known it was you!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nPudding\n\nPudding who?\n\nPudding on your shoes before your trousers is a bad idea!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nQuiet Tina\n\nQuiet Tina who?\n\nQuiet Tina library!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nQuacker\n\nQuacker who?\n\nQuacker another bad joke and I'm leaving!\n\n\n", 
             "\n\nKnock, Knock.\n\nWho's there?\n\nInterrupting raven.\n\nInterrupt...\n\nCAAWW!!!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nRazor.\n\nRazor who?\n\nRazor hands and dance the boogie!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nRadio\n\nRadio who?\n\nRadio not, here I come!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nRough\n\nRough who?\n\nRough, rough, rough! It's your dog!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nRay\n\nRay who?\n\nRay-member me?!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nRobin!\n\nRobin who?\n\nRobin your house!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nRiot\n\nRiot who?\n\nRiot on time here I am.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nRussell\n\nRussell who?\n\nRussell up something to eat, I'm starving!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nSorry\n\nSorry who?\n\nSorry wrong door!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nSherwood\n\nSherwood who?\n\nSure would like you to open the door!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nSacha!\n\nSacha who?\n\nSacha lot of questions!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nSarah\n\nSarah who?\n\nSa-rah phone I could use?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nSnow\n\nSnow who?\n\nSnowbody!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nSpell.\n\nSpell who?\n\nW-H-O\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nSuspense.\n\nSuspense who?\n\n…\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nShocking.\n\nShocking who?\n\nShocking you!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nSomebody too short to ring the doorbell!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nStopwatch.\n\nStopwatch who?\n\nStopwatcha doin’ and open the stupid door.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nTwit\n\nTwit who?\n\nDid anyone else hear an owl?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nTeresa\n\nTeresa who?\n\nTeresa are green!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nTank.\n\nTank who?\n\nYour welcome!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nTennis\n\nTennis who?\n\nTennis is five plus five!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nTad\n\nTad who?\n\nTad's all folks!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nTim\n\nTim who?\n\nTim you got scared!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nTooth\n\nTooth who?\n\nTooth or dare!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nTroy\n\nTroy who?\n\nTroy the bell instead!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nUCI\n\nUCI who?\n\nUCI had to knock because your doorbell didn't work!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nUdder\n\nUdder who?\n\nUdder madness are these knock knock jokes!\n\n\n", 
             "\n\nKnock, knock\n\nWho's there?\n\nUtah\n\nUtah who?\n\nUtah one who told me to knock!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nVenice\n\nVenice who?\n\nVenice your mother coming home?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nVoodoo\n\nVoodoo who?\n\nVoodoo you think you are!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nWooden shoe!\n\nWooden shoe who?\n\nWooden shoe like to know!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nWooden shoe. \n\nWooden shoe who? \n\nWooden shoe like to hear another joke?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nWater?\n\nWater who?\n\nWater way to answer the door!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nWire\n\nWire who?\n\nWire you asking me?\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nWill\n\nWill who?\n\nWill you let me in?\n\n\n", 
             "\n\nWill you remember in a year?\n\nYes.\n\nWill you remember in a month?\n\nYes.\n\nWill you remember in a week?\n\nYes.\n\nWill you remember in a day?\n\nYes.\n\nKnock, knock\n\nWho's there?\n\nYou forgot me already!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nWaiter\n\nWaiter who?\n\nWaiter I get my hands on you!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nX\n\nX who?\n\nX for breakfast!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nYa.\n\nYa who?\n\nWow. You sure are excited to see me!\n\n\n", 
             "\n\nKnock, knock!\n\nWho’s there?\n\nYah!\n\nYah who?\n\nWell, no thanks, I’m more of a Google person.\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nYork\n\nYork who?\n\nYork coming over to my place!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nYugo\n\nYugo who?\n\nYugo first, I'm right behind you!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nZoom\n\nZoom who?\n\nZoom did you expect!\n\n\n", 
             "\n\nKnock, knock.\n\nWho's there?\n\nZany\n\nZany who?\n\nZany body home?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nCandice.\n\nCandice who?\n\nCandice door open, or am I stuck out here?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nSays.\n\nSays who?\n\nSays me, that’s who!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nVoodoo.\n\nVoodoo who?\n\nVoodoo you think you are, asking all these questions?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nMikey.\n\nMikey who?\n\nMikey isn’t working, can you let me in?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nScold.\n\nScold who?\n\nScold outside, let me in!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nNeedle.\n\nNeedle who?\n\nNeedle little help getting in the door!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nHike.\n\nHike who?\n\nI didn’t know you liked Japanese poetry!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nI am.\n\nI am who?\n\nYou tell me!!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nOink oink.\n\nOink oink who?\n\nMake up your mind—are you a pig, or an owl?!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nGladys.\n\nGladys, who?\n\nGladys the weekend—no homework!\n\n\n", 
             "\n\nKnock, knock.\n\nWho’s there?\n\nWooden shoe.\n\nWooden shoe, who?\n\nWooden shoe like to know!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nFigs.\n\nFigs who?\n\nFigs the doorbell, it’s broken!\n\n\n", 
             "\n\nKnock Knock!\n\nWho’s There?\n\nSnow!\n\nSnow who?\n\nSnow laughing matter.\n\n\n", 
             "\n\nKnock, knock!\n\nWho’s there?\n\nWire.\n\nWire who?\n\nWire you always asking ‘who’s there’?\n\n\n", 
             "\n\nKnock, knock!\n\nWho’s there?\n\nAbe.\n\nAbe who?\n\nAbe CDEFJH…\n\n\n", 
             "\n\nKnock, Knock!\n\nWho’s there?\n\nKen\n\nKen who?\n\nKen I come in? It’s cold out here.\n\n\n", 
             "\n\nKnock, Knock!\n\nWho’s there?\n\nWitch.\n\nWitch who?\n\nWitch one of you will give me some Halloween candy?\n\n\n", 
             "\n\nKnock, knock!\n\nWho’s there?\n\nEysore\n\nEysore who?\n\nEysore do love you!\n\n\n", 
             "\n\nKnock, knock\n\nWho’s there?\n\nLeaf\n\nLeaf Who?\n\nLeaf Me Alone!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nRadio.\n\nRadio who?\n\nRadio not, here I come!\n\n\n", 
             "\n\nKnock, Knock\n\nWho’s there?\n\nCargo!\n\nCargo who?\n\nCar go beep, beep!\n\n\n", 
             "\n\nKnock, knock\n\nWho’s there?\n\nAmarillo\n\nAmarillo who?\n\nAmarillo nice guy!\n\n\n", 
             "\n\nKnock, knock\n\nWho’s there?\n\nNun\n\nNun who?\n\nNun of your business!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nWooden shoe.\n\nWooden shoe who?\n\nWooden shoe like to hear another joke?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nA broken pencil.\n\nA broken pencil who?\n\nNever mind, it’s pointless.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nRobin.\n\nRobin who?\n\nRobin you—hand over the cash!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nHowl.\n\nHowl who?\n\nHowl you know if you don’t open the door?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nCash.\n\nCash who?\n\nNo thanks, I prefer peanuts.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nOwls say\n\nOwls say who?\n\nYes, they do.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nArt\n\nArt who?\n\nR2-D2, of course.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nKanga\n\nKanga who?\n\nActually, it’s kangaroo.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nDeja\n\nDeja who?\n\nKnock! Knock!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nNo one\n\nNo one who?\n\n*Remains silent*\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nInterrupting cow\n\nInterruptin-\n\nMooooo!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nAn extraterrestrial\n\nAn extraterrestrial who?\n\nWait–how many extraterrestrials do you know?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nOpportunity\n\nThat’s impossible. Opportunity doesn’t come knocking twice!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nSays\n\nSays who?\n\nSays me, that’s who!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nHoneybee\n\nHoneybee who?\n\nHoneybee a dear and open the door, please.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nStopwatch\n\nStopwatch who?\n\nStopwatch you’re doing and pay attention!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nEurope\n\nEurope who?\n\nNo, you’re a poo!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nCandice\n\nCandice who?\n\nCandice door open, or what?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nSpell\n\nSpell who?\n\nW-H-O\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nVoodoo\n\nVoodoo who?\n\nVoodoo you think you are asking me so many questions?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nHoneydew\n\nHoneydew who?\n\nHoneydew you want to hear some garden jokes?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nTwo knee\n\nTwo knee who?\n\nTwo knee fish!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nWater\n\nWater who?\n\nWater those plants or they’re going to die!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nCash\n\nCash who?\n\nNo thanks, but I’d love some peanuts!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nTurnip\n\nTurnip who?\n\nTurnip the volume, I love this song!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nClosure\n\nClosure who?\n\nClosure mouth while you’re chewing!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nBeets\n\nBeets who?\n\nBeets me!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nGodiva\n\nGodiva who?\n\nGodiva terrible headache, do you have an aspirin?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nLoaf\n\nLoaf who?\n\nI don’t just like bread, I loaf it.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nPecan\n\nPecan who?\n\nPecan somebody your own size!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nControl Freak.\n\nCon—\n\nOkay, now you say, “Control Freak who?”\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nImpatient cow.\n\nImpatient co…\n\nMOO!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nOlive.\n\nOlive who?\n\nOlive you and I don’t care who knows it!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nHo-ho.\n\nHo-ho who?\n\nYou know, your Santa impression could use a little work.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nHanna.\n\nHanna who?\n\n…Hanna partridge in a pear tree!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nMary and Abbey.\n\nMary and Abbey who?\n\nMary Christmas and Abbey New Year!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nIrish.\n\nIrish who?\n\nIrish you a Merry Christmas!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nSanta.\n\nSanta who?\n\nSanta email reminding you I’d be here, and you STILL make me wait in the cold!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nSnow.\n\nSnow who?\n\nSnow use. I forgot my name again!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nYule log.\n\nYule log who?\n\nYule log the door after you let me in, won’t you?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nCarmen.\n\nCarmen who?\n\nCarmen let me in already!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nConvex.\n\nConvex who?\n\nConvex go to prison!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nYa.\n\nYa who?\n\nI’m excited to see you too!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nSherlock.\n\nSherlock who?\n\nSherlock your door shut tight.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nScold.\n\nScold who?\n\nScold outside—let me in!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nRobin.\n\nRobin who?\n\nRobin you! Hand over your cash!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nPolice.\n\nPolice who?\n\nPolice hurry—I’m freezing out here!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nOtto.\n\nOtto who?\n\nOtto know what’s taking you so long!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nOrange.\n\nOrange who?\n\nOrange you gonna open the door?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nNoah.\n\nNoah who?\n\nNoah any place I can get a bite to eat?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nNeedle.\n\nNeedle who?\n\nNeedle little help gettin’ in the door.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nNana.\n\nNana who?\n\nNana your business who’s there.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nLuke.\n\nLuke who?\n\nLuke through the keyhole to see!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nLettuce.\n\nLettuce who?\n\nLettuce in already!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nKetchup.\n\nKetchup who?\n\nKetchup with me and I’ll tell you!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nJustin.\n\nJustin who?\n\nJustin the neighborhood and thought I’d come over.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nIsabelle.\n\nIsabelle who?\n\nIsabelle working, or should I keep knocking?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nHarry.\n\nHarry who?\n\nHarry up and let me in!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nH.\n\nH who?\n\nBless you!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nGoat.\n\nGoat who?\n\nGoat to the door to see who’s knocking!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nDozen.\n\nDozen who?\n\nDozen anyone want to let me in?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nDishes.\n\nDishes who?\n\nDishes a nice place you got here.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nClaire.\n\nClaire who?\n\nClaire the way; I’m coming in!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nCash.\n\nCash who?\n\nI didn’t realize you were some kind of nut!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nCanoe.\n\nCanoe who?\n\nCanoe open the door?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nBoo hoo.\n\nBoo hoo who?\n\nAww, don’t cry—it’s just a joke.\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nBen.\n\nBen who?\n\nBen knocking for 20 minutes!\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nAvenue.\n\nAvenue who?\n\nAvenue knocked on this door before?\n\n\n", 
             "\n\nKnock! Knock!\n\nWho’s there?\n\nAlpaca.\n\nAlpaca who?\n\nAlpaca the suitcase, you load up the car!\n\n\n", 
             "\n\nKnock knock.\n\nWho’s there?\n\nTo.\n\nTo who?\n\nNo, to whom.\n\n\n"
  )
  
  joke <- sample(jokes, 1)
  
  cat(joke)
  
}